// @flow

export default {
    DATA_REQUESTED: 'DATA_REQUESTED',
    DATA_SUCCEEDED: 'DATA_SUCCEEDED',
    DATA_FAILED: 'DATA_FAILED',

    UPDATE_SEARCH_TERM: 'UPDATE_SEARCH_TERM',

    TOGGLE_MENU_MORE: 'TOGGLE_MENU_MORE',

    BOOKMARKS_REQUESTED: 'BOOKMARKS_REQUESTED',
    BOOKMARKS_SUCCEEDED: 'BOOKMARKS_SUCCEEDED',
    BOOKMARKS_FAILED: 'BOOKMARKS_FAILED',

    UPDATE_BOOKMARKS_SUCCEEDED: 'UPDATE_BOOKMARKS_SUCCEEDED',
    UPDATE_BOOKMARKS_FAILED: 'UPDATE_BOOKMARKS_FAILED',
};